version: '1'

services:
  syncdeck:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    restart: always
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/syncdeck
